### ISSUE TITLE
Add a metrics download option

### ISSUE THREAD

**Issue by lvoytek** [lvoytek/discourse-triage#12]
A nice feature to have for technical authors would be an option that downloads data/metrics for a certain time period and saves them to a csv. This could include info such as editors, number of comments, number of edits, size of edits, etc in a category. The argument could look something like:

dsctriage --csv-by-editor [edits,topics] <start> <end> or dsctriage --csv-by-topic [edits,editors,comments]

**Comment by s-makin** [comment]
Thanks Lena, this looks awesome! 

Just to summarise our earlier discussion, the things we would like to be able to track are:
* Contributions (new posts that are included in the docs, edits to existing docs, and comments)
* Contributors (Individual editors by username + flag whether they are internal/external to Canonical)
* Dates of contributions
* Approximate size or scale of contributions (by some metric TBD, e.g. percentage/number of words edited out of original total wordcount)
* General engagement (comments and/or likes over some time period)
Tracking the contributions and contributors will allow us to see who's contributing and make sure that we recognise those contributions.

It would be extremely helpful to be able to use the existing dsctriage function of specifying date ranges to be able to do before/after comparisons to see whether docs changes have led to any quantifiable change in contributions. Or to just be able to see any changes from month-to-month.

Also, being able to track the "lag" between someone posting a comment and then receiving a response. This would probably take the form of checking the dates/times between successive comments, and a flag for whether the posters are internal/external. The idea would be to measure the trend of how a team improves its response rates over time, rather than highlighting specific examples. Excluding "hot topics" with multiple responses in a short time frame would probably be worthwhile. 

Having a basic panel of pre-set graphs produced and saved would be helpful for those who aren't as comfortable with Python analytics. E.g. for specified time frame:
Frequency of new post contributions (external vs internal)
Frequency of edits (external vs internal)
Rolling average of lag time (between comments and replies)
Most/least popular posts by engagement (likes, comments)
(for example)
I'll need to play with some real data myself to be able to see what can be usefully extracted, but could be good to start with.

Thanks again for your work on this, if there's anything I can provide please let me know!

**Comment by lvoytek** [comment]
This use case was ultimately solved by https://github.com/lvoytek/discourse-data-exporter, marking as closed.
